### ISSUE TITLE
colorTemperature question

### ISSUE THREAD

**Issue by guyluz11** [janstol/yeedart#11]
In the documentation of the code it is written that

`  /// * [colorTemperature] - target color temperature (1700 - 6500 K).`

What will happen if I will execute `setColorTemperature` with color temperature smaller than 1700 or bigger than 6500?.

Will it round it to the closes similar value or the request will fail to change the color temperature at all?.

**Comment by janstol** [comment]
I don't know. The documentation does not specify it and I haven't tried that myself.

**Comment by guyluz11** [comment]
Thanks
